/**
 * This class is generated by jOOQ
 */
package main.java.nl.tue.ieis.is.basex.entities.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import main.java.nl.tue.ieis.is.basex.entities.jooq.BasexDatabase;
import main.java.nl.tue.ieis.is.basex.entities.jooq.Keys;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.records.BmActorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BmActor extends TableImpl<BmActorRecord> {

    private static final long serialVersionUID = -1121873332;

    /**
     * The reference instance of <code>basex_database.bm_actor</code>
     */
    public static final BmActor BM_ACTOR = new BmActor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BmActorRecord> getRecordType() {
        return BmActorRecord.class;
    }

    /**
     * The column <code>basex_database.bm_actor.BM_ACTOR_ID</code>.
     */
    public final TableField<BmActorRecord, String> BM_ACTOR_ID = createField("BM_ACTOR_ID", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>basex_database.bm_actor.ACTOR_ID</code>.
     */
    public final TableField<BmActorRecord, String> ACTOR_ID = createField("ACTOR_ID", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>basex_database.bm_actor.BM_ID</code>.
     */
    public final TableField<BmActorRecord, String> BM_ID = createField("BM_ID", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

    /**
     * The column <code>basex_database.bm_actor.IS_FOCAL</code>.
     */
    public final TableField<BmActorRecord, Byte> IS_FOCAL = createField("IS_FOCAL", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>basex_database.bm_actor.IS_CUSTOMER</code>.
     */
    public final TableField<BmActorRecord, Byte> IS_CUSTOMER = createField("IS_CUSTOMER", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>basex_database.bm_actor.VALUE_PROPOSITION</code>.
     */
    public final TableField<BmActorRecord, String> VALUE_PROPOSITION = createField("VALUE_PROPOSITION", org.jooq.impl.SQLDataType.VARCHAR.length(150).nullable(false), this, "");

    /**
     * Create a <code>basex_database.bm_actor</code> table reference
     */
    public BmActor() {
        this("bm_actor", null);
    }

    /**
     * Create an aliased <code>basex_database.bm_actor</code> table reference
     */
    public BmActor(String alias) {
        this(alias, BM_ACTOR);
    }

    private BmActor(String alias, Table<BmActorRecord> aliased) {
        this(alias, aliased, null);
    }

    private BmActor(String alias, Table<BmActorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BasexDatabase.BASEX_DATABASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BmActorRecord> getPrimaryKey() {
        return Keys.KEY_BM_ACTOR_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BmActorRecord>> getKeys() {
        return Arrays.<UniqueKey<BmActorRecord>>asList(Keys.KEY_BM_ACTOR_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<BmActorRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BmActorRecord, ?>>asList(Keys.FK_BM_ACTOR_ACTOR1, Keys.FK_BM_ACTOR_BUSINESS_MODEL1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmActor as(String alias) {
        return new BmActor(alias, this);
    }

    /**
     * Rename this table
     */
    public BmActor rename(String name) {
        return new BmActor(name, null);
    }
}
