/**
 * This class is generated by jOOQ
 */
package main.java.nl.tue.ieis.is.basex.entities.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.Actor;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.BmActor;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.BusinessModel;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.Company;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.CostBenefit;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.CostBenefitActor;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.CpActivity;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.LocationGui;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.Strategy;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.User;
import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.UserHasStrategy;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BasexDatabase extends SchemaImpl {

    private static final long serialVersionUID = -233371991;

    /**
     * The reference instance of <code>basex_database</code>
     */
    public static final BasexDatabase BASEX_DATABASE = new BasexDatabase();

    /**
     * The table <code>basex_database.actor</code>.
     */
    public final Actor ACTOR = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.Actor.ACTOR;

    /**
     * The table <code>basex_database.bm_actor</code>.
     */
    public final BmActor BM_ACTOR = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.BmActor.BM_ACTOR;

    /**
     * The table <code>basex_database.business_model</code>.
     */
    public final BusinessModel BUSINESS_MODEL = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.BusinessModel.BUSINESS_MODEL;

    /**
     * The table <code>basex_database.company</code>.
     */
    public final Company COMPANY = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.Company.COMPANY;

    /**
     * The table <code>basex_database.cost_benefit</code>.
     */
    public final CostBenefit COST_BENEFIT = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.CostBenefit.COST_BENEFIT;

    /**
     * The table <code>basex_database.cost_benefit_actor</code>.
     */
    public final CostBenefitActor COST_BENEFIT_ACTOR = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.CostBenefitActor.COST_BENEFIT_ACTOR;

    /**
     * The table <code>basex_database.cp_activity</code>.
     */
    public final CpActivity CP_ACTIVITY = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.CpActivity.CP_ACTIVITY;

    /**
     * The table <code>basex_database.location_gui</code>.
     */
    public final LocationGui LOCATION_GUI = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.LocationGui.LOCATION_GUI;

    /**
     * The table <code>basex_database.strategy</code>.
     */
    public final Strategy STRATEGY = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.Strategy.STRATEGY;

    /**
     * The table <code>basex_database.user</code>.
     */
    public final User USER = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.User.USER;

    /**
     * The table <code>basex_database.user_has_strategy</code>.
     */
    public final UserHasStrategy USER_HAS_STRATEGY = main.java.nl.tue.ieis.is.basex.entities.jooq.tables.UserHasStrategy.USER_HAS_STRATEGY;

    /**
     * No further instances allowed
     */
    private BasexDatabase() {
        super("basex_database", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Actor.ACTOR,
            BmActor.BM_ACTOR,
            BusinessModel.BUSINESS_MODEL,
            Company.COMPANY,
            CostBenefit.COST_BENEFIT,
            CostBenefitActor.COST_BENEFIT_ACTOR,
            CpActivity.CP_ACTIVITY,
            LocationGui.LOCATION_GUI,
            Strategy.STRATEGY,
            User.USER,
            UserHasStrategy.USER_HAS_STRATEGY);
    }
}
