/**
 * This class is generated by jOOQ
 */
package main.java.nl.tue.ieis.is.basex.entities.jooq.tables.records;


import javax.annotation.Generated;

import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.BmActor;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BmActorRecord extends UpdatableRecordImpl<BmActorRecord> implements Record6<String, String, String, Byte, Byte, String> {

    private static final long serialVersionUID = 848897988;

    /**
     * Setter for <code>basex_database.bm_actor.BM_ACTOR_ID</code>.
     */
    public void setBmActorId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>basex_database.bm_actor.BM_ACTOR_ID</code>.
     */
    public String getBmActorId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>basex_database.bm_actor.ACTOR_ID</code>.
     */
    public void setActorId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>basex_database.bm_actor.ACTOR_ID</code>.
     */
    public String getActorId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>basex_database.bm_actor.BM_ID</code>.
     */
    public void setBmId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>basex_database.bm_actor.BM_ID</code>.
     */
    public String getBmId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>basex_database.bm_actor.IS_FOCAL</code>.
     */
    public void setIsFocal(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>basex_database.bm_actor.IS_FOCAL</code>.
     */
    public Byte getIsFocal() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>basex_database.bm_actor.IS_CUSTOMER</code>.
     */
    public void setIsCustomer(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>basex_database.bm_actor.IS_CUSTOMER</code>.
     */
    public Byte getIsCustomer() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>basex_database.bm_actor.VALUE_PROPOSITION</code>.
     */
    public void setValueProposition(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>basex_database.bm_actor.VALUE_PROPOSITION</code>.
     */
    public String getValueProposition() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Byte, Byte, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Byte, Byte, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BmActor.BM_ACTOR.BM_ACTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BmActor.BM_ACTOR.ACTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BmActor.BM_ACTOR.BM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return BmActor.BM_ACTOR.IS_FOCAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return BmActor.BM_ACTOR.IS_CUSTOMER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BmActor.BM_ACTOR.VALUE_PROPOSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBmActorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getActorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIsFocal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIsCustomer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getValueProposition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmActorRecord value1(String value) {
        setBmActorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmActorRecord value2(String value) {
        setActorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmActorRecord value3(String value) {
        setBmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmActorRecord value4(Byte value) {
        setIsFocal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmActorRecord value5(Byte value) {
        setIsCustomer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmActorRecord value6(String value) {
        setValueProposition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BmActorRecord values(String value1, String value2, String value3, Byte value4, Byte value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BmActorRecord
     */
    public BmActorRecord() {
        super(BmActor.BM_ACTOR);
    }

    /**
     * Create a detached, initialised BmActorRecord
     */
    public BmActorRecord(String bmActorId, String actorId, String bmId, Byte isFocal, Byte isCustomer, String valueProposition) {
        super(BmActor.BM_ACTOR);

        set(0, bmActorId);
        set(1, actorId);
        set(2, bmId);
        set(3, isFocal);
        set(4, isCustomer);
        set(5, valueProposition);
    }
}
