/**
 * This class is generated by jOOQ
 */
package main.java.nl.tue.ieis.is.basex.entities.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.BusinessModel;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record4;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusinessModelRecord extends UpdatableRecordImpl<BusinessModelRecord> implements Record10<String, String, String, String, Double, byte[], Timestamp, Timestamp, String, String> {

    private static final long serialVersionUID = -1789236759;

    /**
     * Setter for <code>basex_database.business_model.BM_ID</code>.
     */
    public void setBmId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>basex_database.business_model.BM_ID</code>.
     */
    public String getBmId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>basex_database.business_model.VALUE_IN_USE</code>.
     */
    public void setValueInUse(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>basex_database.business_model.VALUE_IN_USE</code>.
     */
    public String getValueInUse() {
        return (String) get(1);
    }

    /**
     * Setter for <code>basex_database.business_model.DESC</code>.
     */
    public void setDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>basex_database.business_model.DESC</code>.
     */
    public String getDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>basex_database.business_model.STRATEGY_ID</code>.
     */
    public void setStrategyId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>basex_database.business_model.STRATEGY_ID</code>.
     */
    public String getStrategyId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>basex_database.business_model.VERSION</code>.
     */
    public void setVersion(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>basex_database.business_model.VERSION</code>.
     */
    public Double getVersion() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>basex_database.business_model.IMAGE</code>.
     */
    public void setImage(byte[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>basex_database.business_model.IMAGE</code>.
     */
    public byte[] getImage() {
        return (byte[]) get(5);
    }

    /**
     * Setter for <code>basex_database.business_model.CREATED_DATE</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>basex_database.business_model.CREATED_DATE</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>basex_database.business_model.LAST_EDITED_TIME</code>.
     */
    public void setLastEditedTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>basex_database.business_model.LAST_EDITED_TIME</code>.
     */
    public Timestamp getLastEditedTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>basex_database.business_model.CREATED_BY</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>basex_database.business_model.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>basex_database.business_model.LAST_EDITED_BY</code>.
     */
    public void setLastEditedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>basex_database.business_model.LAST_EDITED_BY</code>.
     */
    public String getLastEditedBy() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record4<String, String, String, String> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, Double, byte[], Timestamp, Timestamp, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, Double, byte[], Timestamp, Timestamp, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return BusinessModel.BUSINESS_MODEL.BM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BusinessModel.BUSINESS_MODEL.VALUE_IN_USE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BusinessModel.BUSINESS_MODEL.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BusinessModel.BUSINESS_MODEL.STRATEGY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return BusinessModel.BUSINESS_MODEL.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field6() {
        return BusinessModel.BUSINESS_MODEL.IMAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return BusinessModel.BUSINESS_MODEL.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return BusinessModel.BUSINESS_MODEL.LAST_EDITED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BusinessModel.BUSINESS_MODEL.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return BusinessModel.BUSINESS_MODEL.LAST_EDITED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getValueInUse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStrategyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value6() {
        return getImage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastEditedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLastEditedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value1(String value) {
        setBmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value2(String value) {
        setValueInUse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value3(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value4(String value) {
        setStrategyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value5(Double value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value6(byte[] value) {
        setImage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value7(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value8(Timestamp value) {
        setLastEditedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value9(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord value10(String value) {
        setLastEditedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusinessModelRecord values(String value1, String value2, String value3, String value4, Double value5, byte[] value6, Timestamp value7, Timestamp value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BusinessModelRecord
     */
    public BusinessModelRecord() {
        super(BusinessModel.BUSINESS_MODEL);
    }

    /**
     * Create a detached, initialised BusinessModelRecord
     */
    public BusinessModelRecord(String bmId, String valueInUse, String desc, String strategyId, Double version, byte[] image, Timestamp createdDate, Timestamp lastEditedTime, String createdBy, String lastEditedBy) {
        super(BusinessModel.BUSINESS_MODEL);

        set(0, bmId);
        set(1, valueInUse);
        set(2, desc);
        set(3, strategyId);
        set(4, version);
        set(5, image);
        set(6, createdDate);
        set(7, lastEditedTime);
        set(8, createdBy);
        set(9, lastEditedBy);
    }
}
