/**
 * This class is generated by jOOQ
 */
package main.java.nl.tue.ieis.is.basex.entities.jooq.tables.records;


import javax.annotation.Generated;

import main.java.nl.tue.ieis.is.basex.entities.jooq.tables.LocationGui;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationGuiRecord extends UpdatableRecordImpl<LocationGuiRecord> implements Record6<String, String, String, Double, Double, Double> {

    private static final long serialVersionUID = -1426546094;

    /**
     * Setter for <code>basex_database.location_gui.COMPONENT_ID</code>.
     */
    public void setComponentId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>basex_database.location_gui.COMPONENT_ID</code>.
     */
    public String getComponentId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>basex_database.location_gui.BM_ID</code>.
     */
    public void setBmId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>basex_database.location_gui.BM_ID</code>.
     */
    public String getBmId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>basex_database.location_gui.BM_ACTOR_ID</code>.
     */
    public void setBmActorId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>basex_database.location_gui.BM_ACTOR_ID</code>.
     */
    public String getBmActorId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>basex_database.location_gui.X</code>.
     */
    public void setX(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>basex_database.location_gui.X</code>.
     */
    public Double getX() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>basex_database.location_gui.Y</code>.
     */
    public void setY(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>basex_database.location_gui.Y</code>.
     */
    public Double getY() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>basex_database.location_gui.Degree</code>.
     */
    public void setDegree(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>basex_database.location_gui.Degree</code>.
     */
    public Double getDegree() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Double, Double, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Double, Double, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return LocationGui.LOCATION_GUI.COMPONENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return LocationGui.LOCATION_GUI.BM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return LocationGui.LOCATION_GUI.BM_ACTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return LocationGui.LOCATION_GUI.X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return LocationGui.LOCATION_GUI.Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return LocationGui.LOCATION_GUI.DEGREE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getComponentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBmActorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getDegree();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationGuiRecord value1(String value) {
        setComponentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationGuiRecord value2(String value) {
        setBmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationGuiRecord value3(String value) {
        setBmActorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationGuiRecord value4(Double value) {
        setX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationGuiRecord value5(Double value) {
        setY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationGuiRecord value6(Double value) {
        setDegree(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationGuiRecord values(String value1, String value2, String value3, Double value4, Double value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationGuiRecord
     */
    public LocationGuiRecord() {
        super(LocationGui.LOCATION_GUI);
    }

    /**
     * Create a detached, initialised LocationGuiRecord
     */
    public LocationGuiRecord(String componentId, String bmId, String bmActorId, Double x, Double y, Double degree) {
        super(LocationGui.LOCATION_GUI);

        set(0, componentId);
        set(1, bmId);
        set(2, bmActorId);
        set(3, x);
        set(4, y);
        set(5, degree);
    }
}
