-- MySQL Script generated by MySQL Workbench
-- 12/05/16 22:13:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema basex_database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `basex_database` ;

-- -----------------------------------------------------
-- Schema basex_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basex_database` DEFAULT CHARACTER SET latin1 ;
USE `basex_database` ;

-- -----------------------------------------------------
-- Table `basex_database`.`ACTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`ACTOR` (
  `ACTOR_NAME` NVARCHAR(150) NOT NULL,
  `ACTOR_DESC` NVARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`ACTOR_NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `basex_database`.`STRATEGY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`STRATEGY` (
  `STRATEGY_NAME` NVARCHAR(50) NOT NULL,
  `STRATEGY_DESC` NVARCHAR(350) NULL DEFAULT NULL,
  PRIMARY KEY (`STRATEGY_NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `basex_database`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`USER` (
  `EMAIL` NVARCHAR(100) NOT NULL,
  `PASSWORD` NVARCHAR(50) NOT NULL,
  `LASTNAME` NVARCHAR(150) NULL DEFAULT NULL,
  `FIRSTNAME` NVARCHAR(150) NULL DEFAULT NULL,
  `COMPANY` NVARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`EMAIL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `basex_database`.`BUSINESS_MODEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`BUSINESS_MODEL` (
  `VALUE_IN_USE` NVARCHAR(150) NOT NULL,
  `STRATEGY_NAME` NVARCHAR(50) NOT NULL,
  `DESC` NVARCHAR(5000) NULL DEFAULT NULL,
  `VERSION` FLOAT(2,2) NOT NULL,
  `IMAGE` BLOB NULL DEFAULT NULL,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` NVARCHAR(100) NOT NULL,
  `LAST_EDITED_AT` DATETIME NOT NULL,
  `LAST_EDITED_BY` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`VALUE_IN_USE`, `STRATEGY_NAME`, `CREATED_BY`, `LAST_EDITED_BY`),
  INDEX `fk_BUSINESS_MODEL_STRATEGY1_idx` (`STRATEGY_NAME` ASC),
  INDEX `fk_BUSINESS_MODEL_USER1_idx` (`CREATED_BY` ASC),
  INDEX `fk_BUSINESS_MODEL_USER2_idx` (`LAST_EDITED_BY` ASC),
  CONSTRAINT `fk_BUSINESS_MODEL_STRATEGY1`
    FOREIGN KEY (`STRATEGY_NAME`)
    REFERENCES `basex_database`.`STRATEGY` (`STRATEGY_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BUSINESS_MODEL_USER1`
    FOREIGN KEY (`CREATED_BY`)
    REFERENCES `basex_database`.`USER` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BUSINESS_MODEL_USER2`
    FOREIGN KEY (`LAST_EDITED_BY`)
    REFERENCES `basex_database`.`USER` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `basex_database`.`BM_ACTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`BM_ACTOR` (
  `BM_ACTOR_ID` VARCHAR(301) NOT NULL,
  `BM_VALUE_IN_USE` NVARCHAR(150) NOT NULL,
  `ACTOR_NAME` NVARCHAR(150) NOT NULL,
  `IS_FOCAL` TINYINT(1) NOT NULL,
  `IS_CUSTOMER` TINYINT(1) NOT NULL,
  `VALUE_PROPOSITION` NVARCHAR(150) NOT NULL,
  PRIMARY KEY (`BM_ACTOR_ID`, `BM_VALUE_IN_USE`, `ACTOR_NAME`),
  INDEX `fk_BM_ACTOR_ACTOR1_idx` (`ACTOR_NAME` ASC),
  CONSTRAINT `fk_BM_ACTOR_BUSINESS_MODEL1`
    FOREIGN KEY (`BM_VALUE_IN_USE`)
    REFERENCES `basex_database`.`BUSINESS_MODEL` (`VALUE_IN_USE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BM_ACTOR_ACTOR1`
    FOREIGN KEY (`ACTOR_NAME`)
    REFERENCES `basex_database`.`ACTOR` (`ACTOR_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `basex_database`.`COST_BENEFIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`COST_BENEFIT` (
  `CB_NAME` NVARCHAR(50) NOT NULL,
  `CB_DESC` VARCHAR(350) NULL,
  PRIMARY KEY (`CB_NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `basex_database`.`CP_ACTIVITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`CP_ACTIVITY` (
  `ACT_NAME` NVARCHAR(159) NOT NULL,
  PRIMARY KEY (`ACT_NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basex_database`.`STRATEGY_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`STRATEGY_USER` (
  `STRATEGY_NAME` NVARCHAR(50) NOT NULL,
  `USER_EMAIL` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`STRATEGY_NAME`, `USER_EMAIL`),
  INDEX `fk_STRATEGY_has_USER_USER1_idx` (`USER_EMAIL` ASC),
  INDEX `fk_STRATEGY_has_USER_STRATEGY1_idx` (`STRATEGY_NAME` ASC),
  CONSTRAINT `fk_STRATEGY_has_USER_STRATEGY1`
    FOREIGN KEY (`STRATEGY_NAME`)
    REFERENCES `basex_database`.`STRATEGY` (`STRATEGY_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STRATEGY_has_USER_USER1`
    FOREIGN KEY (`USER_EMAIL`)
    REFERENCES `basex_database`.`USER` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `basex_database`.`CB_BM_ACTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`CB_BM_ACTOR` (
  `COST_BENEFIT_NAME` NVARCHAR(50) NOT NULL,
  `BM_ACTOR_ID` VARCHAR(301) NOT NULL,
  `COST_OR_BENEFIT` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`COST_BENEFIT_NAME`, `BM_ACTOR_ID`),
  INDEX `fk_COST_BENEFIT_has_BM_ACTOR_BM_ACTOR1_idx` (`BM_ACTOR_ID` ASC),
  INDEX `fk_COST_BENEFIT_has_BM_ACTOR_COST_BENEFIT1_idx` (`COST_BENEFIT_NAME` ASC),
  CONSTRAINT `fk_COST_BENEFIT_has_BM_ACTOR_COST_BENEFIT1`
    FOREIGN KEY (`COST_BENEFIT_NAME`)
    REFERENCES `basex_database`.`COST_BENEFIT` (`CB_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COST_BENEFIT_has_BM_ACTOR_BM_ACTOR1`
    FOREIGN KEY (`BM_ACTOR_ID`)
    REFERENCES `basex_database`.`BM_ACTOR` (`BM_ACTOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `basex_database`.`BM_ACTOR_ACTIVITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basex_database`.`BM_ACTOR_ACTIVITY` (
  `BM_ACTOR_ID` VARCHAR(301) NOT NULL,
  `ACTIVITY_NAME` NVARCHAR(159) NOT NULL,
  PRIMARY KEY (`BM_ACTOR_ID`, `ACTIVITY_NAME`),
  INDEX `fk_BM_ACTOR_has_CP_ACTIVITY_CP_ACTIVITY1_idx` (`ACTIVITY_NAME` ASC),
  INDEX `fk_BM_ACTOR_has_CP_ACTIVITY_BM_ACTOR1_idx` (`BM_ACTOR_ID` ASC),
  CONSTRAINT `fk_BM_ACTOR_has_CP_ACTIVITY_BM_ACTOR1`
    FOREIGN KEY (`BM_ACTOR_ID`)
    REFERENCES `basex_database`.`BM_ACTOR` (`BM_ACTOR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BM_ACTOR_has_CP_ACTIVITY_CP_ACTIVITY1`
    FOREIGN KEY (`ACTIVITY_NAME`)
    REFERENCES `basex_database`.`CP_ACTIVITY` (`ACT_NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
